version: "3.9"

services:
  db:
    build: .
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/recommend-db/:/var/lib/mysql
    networks:
      - nyx-network
    env_file: .env
    container_name: recommend-db-con
    hostname: recommend-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 220M

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
