# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import schema_pb2 as schema__pb2


class RecommendServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendDialog = channel.unary_unary(
                '/schema.RecommendService/RecommendDialog',
                request_serializer=schema__pb2.RecommendRequestDialog.SerializeToString,
                response_deserializer=schema__pb2.RecommendResponseList.FromString,
                )
        self.RecommendSummary = channel.unary_unary(
                '/schema.RecommendService/RecommendSummary',
                request_serializer=schema__pb2.RecommendRequestSummary.SerializeToString,
                response_deserializer=schema__pb2.RecommendResponseList.FromString,
                )


class RecommendServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecommendDialog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendDialog': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendDialog,
                    request_deserializer=schema__pb2.RecommendRequestDialog.FromString,
                    response_serializer=schema__pb2.RecommendResponseList.SerializeToString,
            ),
            'RecommendSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendSummary,
                    request_deserializer=schema__pb2.RecommendRequestSummary.FromString,
                    response_serializer=schema__pb2.RecommendResponseList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schema.RecommendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecommendService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecommendDialog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schema.RecommendService/RecommendDialog',
            schema__pb2.RecommendRequestDialog.SerializeToString,
            schema__pb2.RecommendResponseList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecommendSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schema.RecommendService/RecommendSummary',
            schema__pb2.RecommendRequestSummary.SerializeToString,
            schema__pb2.RecommendResponseList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
