version: "3.9"

services:
  categories-api:
    build: .
    ports:
      - "8050:8050"
    container_name: categories-api-con
    hostname: categories-api-service
    restart: unless-stopped
    env_file:
      - .env-prod
    environment:
      - GIN_MODE=release
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
