version: "3.9"

services:
  summary-api:
    build: .
    container_name: summary-api-con
    hostname: summary-api-service
    restart: unless-stopped
    env_file:
      - .env-prod
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
