version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss:9.5.2
    container_name: grafana
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
