version: "3.9"

services:
  tracking-api:
    build: .
    ports:
      - "8020:8020"
    container_name: tracking-api-con
    hostname: tracking-api-service
    restart: unless-stopped
    env_file:
      - .env-prod
    environment:
      - GIN_MODE=release
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
