# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x06schema\"\x1e\n\x0eSummaryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t2L\n\x0eSummaryService\x12:\n\x07Summary\x12\x16.schema.SummaryRequest\x1a\x17.schema.SummaryResponseB\x04Z\x02./b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _SUMMARYREQUEST._serialized_start=24
  _SUMMARYREQUEST._serialized_end=54
  _SUMMARYRESPONSE._serialized_start=56
  _SUMMARYRESPONSE._serialized_end=90
  _SUMMARYSERVICE._serialized_start=92
  _SUMMARYSERVICE._serialized_end=168
# @@protoc_insertion_point(module_scope)
