version: "3.9"

services:
  couchdb:
    build: .
    container_name: dialog-db
    restart: on-failure
    ports:
      - "5984:5984"
    environment:
      - "COUCHDB_USER=${COUCHDB_USER}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD}"
    volumes:
      - $HOME/couchdb-data/couchdb-data:/opt/couchdb/data
      - $HOME/couchdb-data/couchdb-config:/opt/couchdb/etc/local.d
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
