version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    container_name: dialog-api
    hostname: dialog-service
    restart: on-failure
    env_file:
      - .env-prod
    environment:
      - GIN_MODE=release
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
