version: "3.9"

services:
  dialog-api:
    build: .
    ports:
      - "8080:8080"
    container_name: dialog-api-con
    hostname: dialog-api-service
    restart: unless-stopped
    env_file:
      - .env-prod
    environment:
      - GIN_MODE=release
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
