version: "3.9"

services:
  couchdb:
    image: couchdb:3
    container_name: dialog-db
    restart: on-failure
    ports:
      - "5984:5984"
    environment:
      - "COUCHDB_USER=${COUCHDB_USER}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD}"
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_config:/opt/couchdb/etc/local.d
    networks:
      - nyx-network

volumes:
  couchdb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/couchdb_data
  couchdb_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/couchdb_config

networks:
  nyx-network:
    driver: bridge
