version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: nyx-web-con
    hostname: nyx-web
    restart: unless-stopped
    networks:
      - nyx-network

networks:
  nyx-network:
    name: nyx-network
    driver: bridge
