name: Build categories API

on:
  push:
    branches: [ main ]
    paths:
      - categories-api/**
      - .github/workflows/categories-api.yml
  workflow_dispatch:

jobs:
  build:
    name: Build categories API and push it to AWS ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build Categories API
        env:
          COUCHDB_URL: ${{ secrets.COUCHDB_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          REGISTRY: ${{ secrets.REGISTRY }}
        run: |
          cd categories-api
          echo "COUCHDB_URL=$COUCHDB_URL" >> env/.env
          echo "DB_NAME=$DB_NAME" >> env/.env
          
          docker build -t categories-api .
          docker tag categories-api:latest $REGISTRY/categories-api:latest

      - name: Push categories API to AWS ECR
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: docker push $REGISTRY/categories-api:latest
