name: Build categories API and push it to AWS ECR

on:
  push:
    branches: [ main ]
    paths:
      - categories-api/**
      - .github/workflows/categories-api.yml
  workflow_dispatch:

jobs:
  build:
    name: Build categories API and push it to AWS ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_REGION

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build Categories API
        env:
          COUCHDB_URL: ${{ secrets.COUCHDB_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          cd categories-api
          echo "COUCHDB_URL=$COUCHDB_URL" >> env/.env
          echo "DB_NAME=$DB_NAME" >> env/.env
          
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest .

      - name: Push Categories API to AWS ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
