name: Build couchDB

on:
  push:
    branches: [ main ]
    paths:
      - couchdb/**
      - .github/workflows/couchdb.yml
  workflow_dispatch:

jobs:
  build:
    name: Build couchDB and push it to AWS ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Create .env file
        env:
          COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
          COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
        run: |
          cd couchdb
          echo "COUCHDB_USER=COUCHDB_USER" >> .env
          echo "COUCHDB_PASSWORD=COUCHDB_PASSWORD" >> .env

      - name: Build couchDB
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: |
          cd couchdb
          docker build -t couchdb .
          docker tag couchdb:latest $REGISTRY/couchdb:latest

      - name: Push couchDB to AWS ECR
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: docker push $REGISTRY/couchdb:latest
