name: Build dialog API

on:
  push:
    branches: [ main ]
    paths:
      - dialog-api/**
      - .github/workflows/dialog-api.yml
  workflow_dispatch:

jobs:
  build:
    name: Build dialog API and push it to AWS ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Create .env file
        env:
          COUCHDB_URL: ${{ secrets.COUCHDB_URL }}
          DB_NAME: ${{ secrets.DB_NAME_DIALOG }}
          DIALOG_MODEL: ${{ secrets.DIALOG_MODEL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_DIALOG }}
        run: |
          cd dialog-api
          echo "COUCHDB_URL=$COUCHDB_URL" >> env/.env
          echo "DB_NAME=$DB_NAME" >> env/.env
          echo "DIALOG_MODEL=$DIALOG_MODEL" >> env/.env
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> env/.env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> env/.env
          echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> env/.env

      - name: Create .env-prod
        env:
          COUCHDB_URL: ${{ secrets.COUCHDB_URL_PROD }}
          DIALOG_MODEL: ${{ secrets.DIALOG_MODEL_PROD }}
        run:
          cd dialog-api
          echo "COUCHDB_URL=$COUCHDB_URL" >> .env-prod
          echo "DIALOG_MODEL=$DIALOG_MODEL" >> .env-prod

      - name: Build dialog API
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: |
          cd dialog-api
          docker build -t dialog-api .
          docker tag dialog-api:latest $REGISTRY/dialog-api:latest

      - name: Push dialog API to AWS ECR
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: docker push $REGISTRY/dialog-api:latest
