name: Build dialog model

on:
  push:
    branches: [ main ]
    paths:
      - dialog-model/**
      - .github/workflows/dialog-model.yml
  workflow_dispatch:

jobs:
  build:
    name: Build dialog model and push it to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PROJECT_NAME_DIALOG: ${{ secrets.PROJECT_NAME_DIALOG }}
        with:
          context: "{{defaultContext}}:dialog-model"
          push: true
          tags: ${{ env.USERNAME }}/${{ env.PROJECT_NAME_DIALOG }}:latest
